-- 0003_topics_expansion.sql  (expand routinely-harvested topic list to ~100)
-- CAT-specific control table only (ingest_topics). Additive, idempotent.
-- Weighted toward primary care, general surgery, orthopaedics (the three EHRC
-- service lines we want enriched most), layered on the existing 27 acute-medicine
-- topics (22 seed + 5 Curator-discovered). New rows = 78  ->  ~105 total.

INSERT INTO ingest_topics (topic, query_terms) VALUES
-- ---------- Primary care (34) ----------
 ('Hypertension management',                 'hypertension AND (management OR antihypertensive OR treatment)'),
 ('Type 2 diabetes management',              '"type 2 diabetes" AND (management OR glycemic OR pharmacotherapy)'),
 ('Type 1 diabetes management',             '"type 1 diabetes"'),
 ('Dyslipidemia & statin therapy',           'dyslipidemia OR hyperlipidemia OR statin'),
 ('Hypothyroidism',                          'hypothyroidism OR levothyroxine'),
 ('Chronic kidney disease',                  '"chronic kidney disease"'),
 ('Asthma — chronic management',             'asthma AND (maintenance OR controller OR "long-term management")'),
 ('Stable COPD management',                  '"chronic obstructive pulmonary disease" AND (stable OR maintenance OR management)'),
 ('Major depressive disorder',               '"major depressive disorder" OR depression'),
 ('Generalized anxiety disorder',            '"generalized anxiety disorder" OR "anxiety disorder"'),
 ('Migraine & primary headache',             'migraine OR "tension-type headache"'),
 ('Gastroesophageal reflux disease',         '"gastroesophageal reflux disease" OR GERD'),
 ('Irritable bowel syndrome',                '"irritable bowel syndrome"'),
 ('Urinary tract infection',                 '"urinary tract infection" OR cystitis OR pyelonephritis'),
 ('Gout',                                    'gout OR "gouty arthritis"'),
 ('Osteoporosis',                            'osteoporosis AND (management OR treatment OR "bone mineral density")'),
 ('Obesity management',                      'obesity AND (management OR pharmacotherapy OR "weight loss")'),
 ('Smoking cessation',                       '"smoking cessation" OR "tobacco cessation"'),
 ('Iron deficiency anemia',                  '"iron deficiency anemia"'),
 ('Allergic rhinitis',                       '"allergic rhinitis"'),
 ('Acute otitis media',                      '"otitis media"'),
 ('Streptococcal pharyngitis',               'pharyngitis OR tonsillitis'),
 ('Acute rhinosinusitis',                    'rhinosinusitis OR "acute sinusitis"'),
 ('Cellulitis & soft-tissue infection',      'cellulitis OR "skin and soft tissue infection"'),
 ('Benign prostatic hyperplasia',            '"benign prostatic hyperplasia"'),
 ('Menopause & hormone therapy',             'menopause AND ("hormone therapy" OR management OR "hot flashes")'),
 ('Benign paroxysmal positional vertigo',    '"benign paroxysmal positional vertigo" OR vertigo'),
 ('Chronic insomnia',                        'insomnia AND (management OR treatment OR "cognitive behavioral")'),
 ('Vitamin D deficiency',                    '"vitamin D deficiency" OR "vitamin D supplementation"'),
 ('Heart failure with preserved EF',         '"heart failure with preserved ejection fraction" OR HFpEF'),
 ('Adult immunization',                      '"adult immunization" OR "adult vaccination"'),
 ('Chronic constipation',                    '"chronic constipation"'),
 ('Prediabetes & metabolic syndrome',        'prediabetes OR "metabolic syndrome"'),
 ('Helicobacter pylori infection',           '"Helicobacter pylori" AND (eradication OR treatment)'),
-- ---------- General surgery (22) ----------
 ('Acute appendicitis',                      '"acute appendicitis"'),
 ('Acute cholecystitis & cholelithiasis',    'cholecystitis OR cholelithiasis OR "gallstone disease"'),
 ('Inguinal hernia repair',                  '"inguinal hernia"'),
 ('Ventral & incisional hernia',             '"ventral hernia" OR "incisional hernia"'),
 ('Small bowel obstruction',                 '"small bowel obstruction" OR "intestinal obstruction"'),
 ('Acute diverticulitis',                    'diverticulitis'),
 ('Perforated peptic ulcer',                 '"perforated peptic ulcer" OR "peptic ulcer perforation"'),
 ('Surgical site infection',                 '"surgical site infection"'),
 ('Breast lump evaluation',                  '"breast mass" OR "breast lump"'),
 ('Colorectal cancer screening',             '"colorectal cancer screening" OR colonoscopy'),
 ('Acute abdomen evaluation',                '"acute abdomen"'),
 ('Perianal abscess & anal fistula',         '"perianal abscess" OR "anal fistula"'),
 ('Pilonidal disease',                       '"pilonidal sinus" OR "pilonidal disease"'),
 ('Hemorrhoidal disease',                    'hemorrhoids OR hemorrhoidectomy'),
 ('Acute mesenteric ischemia',               '"mesenteric ischemia"'),
 ('Thyroid nodule & thyroidectomy',          '"thyroid nodule" OR thyroidectomy'),
 ('Varicose veins & venous insufficiency',   '"varicose veins" OR "chronic venous insufficiency"'),
 ('Postoperative ileus',                     '"postoperative ileus"'),
 ('Enhanced recovery after surgery',         '"enhanced recovery after surgery" OR ERAS'),
 ('Necrotizing soft-tissue infection',       '"necrotizing fasciitis" OR "necrotizing soft tissue infection"'),
 ('Acute abdominal trauma',                  '"abdominal trauma" OR "blunt abdominal trauma"'),
 ('Gastrointestinal cancer surgery',         '"gastric cancer" OR "colorectal cancer"'),
-- ---------- Orthopaedics (22) ----------
 ('Hip fracture',                            '"hip fracture" OR "femoral neck fracture"'),
 ('Distal radius (Colles) fracture',         '"distal radius fracture" OR "Colles fracture"'),
 ('Ankle fracture & sprain',                 '"ankle fracture" OR "ankle sprain"'),
 ('ACL injury & reconstruction',             '"anterior cruciate ligament"'),
 ('Meniscal tear',                           '"meniscal tear" OR meniscus'),
 ('Rotator cuff disease',                    '"rotator cuff"'),
 ('Adhesive capsulitis (frozen shoulder)',   '"adhesive capsulitis" OR "frozen shoulder"'),
 ('Carpal tunnel syndrome',                  '"carpal tunnel syndrome"'),
 ('Lumbar disc herniation & sciatica',       '"lumbar disc herniation" OR sciatica OR "lumbar radiculopathy"'),
 ('Cervical radiculopathy & spondylosis',    '"cervical radiculopathy" OR "cervical spondylosis"'),
 ('Knee osteoarthritis',                     '"knee osteoarthritis"'),
 ('Hip osteoarthritis',                      '"hip osteoarthritis"'),
 ('Septic arthritis',                        '"septic arthritis"'),
 ('Osteomyelitis',                           'osteomyelitis'),
 ('Acute compartment syndrome',              '"compartment syndrome"'),
 ('Total knee arthroplasty',                 '"total knee arthroplasty" OR "total knee replacement"'),
 ('Total hip arthroplasty',                  '"total hip arthroplasty" OR "total hip replacement"'),
 ('Plantar fasciitis',                       '"plantar fasciitis"'),
 ('Lateral epicondylitis (tennis elbow)',    '"lateral epicondylitis" OR "tennis elbow"'),
 ('Shoulder dislocation & instability',      '"shoulder dislocation" OR "shoulder instability"'),
 ('Scaphoid fracture',                       '"scaphoid fracture"'),
 ('Low back pain',                           '"low back pain" AND (management OR treatment)')
ON CONFLICT (topic) DO NOTHING;
