// GENERATED by architecture-map-gen.mjs — do not edit by hand; run `npm run architecture:map`.
// CI regenerates this file and fails on any diff (the staleness gate in .github/workflows/ci.yml),
// so what is committed here always matches what the code actually is.

import type { Plane } from './manifests';

export interface MapModule { id: string; plane: Plane | 'unregistered'; }
export interface MapEdge { from: string; to: string; kind: 'value' | 'type'; }
export interface VersionRow { constName: string; value: string; file: string; derived: boolean; }
export interface MapRule { id: number; name: string; sourceGlobs: string[]; }

export const MAP_MODULES: MapModule[] = [
  {
    "id": "admin-cookie",
    "plane": "unregistered"
  },
  {
    "id": "admin-gate",
    "plane": "unregistered"
  },
  {
    "id": "app",
    "plane": "ui"
  },
  {
    "id": "app/admin",
    "plane": "ui"
  },
  {
    "id": "app/api",
    "plane": "ui"
  },
  {
    "id": "app/appropriateness",
    "plane": "ui"
  },
  {
    "id": "app/ask",
    "plane": "ui"
  },
  {
    "id": "app/audit",
    "plane": "ui"
  },
  {
    "id": "app/browse",
    "plane": "ui"
  },
  {
    "id": "app/care",
    "plane": "ui"
  },
  {
    "id": "app/ddx",
    "plane": "ui"
  },
  {
    "id": "app/drugs",
    "plane": "ui"
  },
  {
    "id": "appropriateness-runs",
    "plane": "unregistered"
  },
  {
    "id": "architecture",
    "plane": "infra"
  },
  {
    "id": "as-of-core",
    "plane": "pure-core"
  },
  {
    "id": "audit-suppression-core",
    "plane": "unregistered"
  },
  {
    "id": "audit-suppression-store",
    "plane": "unregistered"
  },
  {
    "id": "calculators",
    "plane": "unregistered"
  },
  {
    "id": "care-call-core",
    "plane": "unregistered"
  },
  {
    "id": "care-call-store",
    "plane": "unregistered"
  },
  {
    "id": "care-cookie",
    "plane": "unregistered"
  },
  {
    "id": "care-tracks",
    "plane": "unregistered"
  },
  {
    "id": "care-tracks-core",
    "plane": "unregistered"
  },
  {
    "id": "care-tracks-store",
    "plane": "unregistered"
  },
  {
    "id": "ccb-apikey",
    "plane": "unregistered"
  },
  {
    "id": "ccb-brief",
    "plane": "unregistered"
  },
  {
    "id": "ccb-brief-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-detect",
    "plane": "unregistered"
  },
  {
    "id": "ccb-dossier",
    "plane": "unregistered"
  },
  {
    "id": "ccb-dossier-cache",
    "plane": "unregistered"
  },
  {
    "id": "ccb-dossier-cache-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-dossier-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-episode-docs-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-extract-cache",
    "plane": "unregistered"
  },
  {
    "id": "ccb-extract-cache-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-fetch",
    "plane": "unregistered"
  },
  {
    "id": "ccb-fetch-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-funnel",
    "plane": "unregistered"
  },
  {
    "id": "ccb-resolve",
    "plane": "unregistered"
  },
  {
    "id": "ccb-search",
    "plane": "unregistered"
  },
  {
    "id": "ccb-search-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-store",
    "plane": "unregistered"
  },
  {
    "id": "ccb-timeline-enrich-core",
    "plane": "unregistered"
  },
  {
    "id": "ccb-worklist-core",
    "plane": "unregistered"
  },
  {
    "id": "charge-master",
    "plane": "unregistered"
  },
  {
    "id": "charge-master-core",
    "plane": "unregistered"
  },
  {
    "id": "citations-core",
    "plane": "unregistered"
  },
  {
    "id": "clinical-state",
    "plane": "pure-core"
  },
  {
    "id": "coach",
    "plane": "unregistered"
  },
  {
    "id": "concordance",
    "plane": "unregistered"
  },
  {
    "id": "concordance-core",
    "plane": "unregistered"
  },
  {
    "id": "concordance-store",
    "plane": "unregistered"
  },
  {
    "id": "curator",
    "plane": "unregistered"
  },
  {
    "id": "db",
    "plane": "unregistered"
  },
  {
    "id": "ddi",
    "plane": "unregistered"
  },
  {
    "id": "ddi-log",
    "plane": "unregistered"
  },
  {
    "id": "ddi-reference",
    "plane": "unregistered"
  },
  {
    "id": "ddi-tags",
    "plane": "unregistered"
  },
  {
    "id": "ddx-constraints",
    "plane": "unregistered"
  },
  {
    "id": "ddx-eval-core",
    "plane": "unregistered"
  },
  {
    "id": "ddx-hypothesis",
    "plane": "unregistered"
  },
  {
    "id": "doc-audit",
    "plane": "unregistered"
  },
  {
    "id": "doc-audit-core",
    "plane": "unregistered"
  },
  {
    "id": "doctor-directory-core",
    "plane": "unregistered"
  },
  {
    "id": "doctor-metrics-refresh",
    "plane": "unregistered"
  },
  {
    "id": "doctor-metrics-store",
    "plane": "unregistered"
  },
  {
    "id": "dose-aggregation-core",
    "plane": "unregistered"
  },
  {
    "id": "dose-limits",
    "plane": "unregistered"
  },
  {
    "id": "drugs",
    "plane": "unregistered"
  },
  {
    "id": "episode-state",
    "plane": "pure-core"
  },
  {
    "id": "europepmc",
    "plane": "unregistered"
  },
  {
    "id": "expand",
    "plane": "unregistered"
  },
  {
    "id": "finding-match-core",
    "plane": "unregistered"
  },
  {
    "id": "formulary",
    "plane": "unregistered"
  },
  {
    "id": "formulary-match-core",
    "plane": "unregistered"
  },
  {
    "id": "gcp-auth",
    "plane": "unregistered"
  },
  {
    "id": "gemini-multimodal",
    "plane": "unregistered"
  },
  {
    "id": "gov-auth",
    "plane": "unregistered"
  },
  {
    "id": "harvest",
    "plane": "unregistered"
  },
  {
    "id": "harvest-epmc",
    "plane": "unregistered"
  },
  {
    "id": "inquiry",
    "plane": "advisory"
  },
  {
    "id": "investigations",
    "plane": "unregistered"
  },
  {
    "id": "ipd-audit",
    "plane": "audit-engine"
  },
  {
    "id": "jats-chunk",
    "plane": "unregistered"
  },
  {
    "id": "lab",
    "plane": "unregistered"
  },
  {
    "id": "lab-batch",
    "plane": "unregistered"
  },
  {
    "id": "lab-batch-core",
    "plane": "unregistered"
  },
  {
    "id": "lab-clinical-core",
    "plane": "unregistered"
  },
  {
    "id": "lab-core",
    "plane": "unregistered"
  },
  {
    "id": "learning",
    "plane": "unregistered"
  },
  {
    "id": "learning-core",
    "plane": "unregistered"
  },
  {
    "id": "learning-flywheel-core",
    "plane": "unregistered"
  },
  {
    "id": "llm",
    "plane": "unregistered"
  },
  {
    "id": "llm-cost",
    "plane": "unregistered"
  },
  {
    "id": "llm-cost-core",
    "plane": "unregistered"
  },
  {
    "id": "lvc",
    "plane": "unregistered"
  },
  {
    "id": "lvc-core",
    "plane": "unregistered"
  },
  {
    "id": "lvc-value",
    "plane": "unregistered"
  },
  {
    "id": "lvc-value-core",
    "plane": "unregistered"
  },
  {
    "id": "mcp-server",
    "plane": "unregistered"
  },
  {
    "id": "mcp-tools",
    "plane": "unregistered"
  },
  {
    "id": "med-audit",
    "plane": "unregistered"
  },
  {
    "id": "member-state",
    "plane": "spine"
  },
  {
    "id": "metabase",
    "plane": "unregistered"
  },
  {
    "id": "mini-backfill",
    "plane": "unregistered"
  },
  {
    "id": "model-labels",
    "plane": "unregistered"
  },
  {
    "id": "model-programme-core",
    "plane": "unregistered"
  },
  {
    "id": "multi-query",
    "plane": "unregistered"
  },
  {
    "id": "ndjson-client",
    "plane": "unregistered"
  },
  {
    "id": "observability-meta",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-cats",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-changelog",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-context-sort",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-doctor",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-pdf",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-store",
    "plane": "unregistered"
  },
  {
    "id": "opd-audit-ui",
    "plane": "unregistered"
  },
  {
    "id": "opd-case-anchor-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-complexity-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-feedback-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-feedback-rollup-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-feedback-ux-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-funnel-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-gov-read",
    "plane": "unregistered"
  },
  {
    "id": "opd-gov-signal-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-gov-signal-store",
    "plane": "unregistered"
  },
  {
    "id": "opd-governance-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-ingest-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-longitudinal",
    "plane": "advisory"
  },
  {
    "id": "opd-lvc-classify-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-note-audit",
    "plane": "unregistered"
  },
  {
    "id": "opd-note-audit-core",
    "plane": "unregistered"
  },
  {
    "id": "opd-note-score-core",
    "plane": "score-arithmetic"
  },
  {
    "id": "opd-triage-core",
    "plane": "advisory"
  },
  {
    "id": "opd-triage-store",
    "plane": "unregistered"
  },
  {
    "id": "pathway",
    "plane": "unregistered"
  },
  {
    "id": "pathway-core",
    "plane": "unregistered"
  },
  {
    "id": "pharmacist-cookie",
    "plane": "unregistered"
  },
  {
    "id": "plos",
    "plane": "unregistered"
  },
  {
    "id": "prognosis-core",
    "plane": "unregistered"
  },
  {
    "id": "proms",
    "plane": "unregistered"
  },
  {
    "id": "pubchem",
    "plane": "unregistered"
  },
  {
    "id": "pubmed",
    "plane": "unregistered"
  },
  {
    "id": "reasoning",
    "plane": "unregistered"
  },
  {
    "id": "record-audit-link-store",
    "plane": "unregistered"
  },
  {
    "id": "rerank",
    "plane": "unregistered"
  },
  {
    "id": "retrieve",
    "plane": "unregistered"
  },
  {
    "id": "review-navigator-core",
    "plane": "unregistered"
  },
  {
    "id": "review-queue-core",
    "plane": "unregistered"
  },
  {
    "id": "review-stats-core",
    "plane": "unregistered"
  },
  {
    "id": "right-care-ground-eval-core",
    "plane": "unregistered"
  },
  {
    "id": "right-care-state",
    "plane": "unregistered"
  },
  {
    "id": "room-rent",
    "plane": "unregistered"
  },
  {
    "id": "room-rent-core",
    "plane": "unregistered"
  },
  {
    "id": "runs-export",
    "plane": "unregistered"
  },
  {
    "id": "rxlabelguard",
    "plane": "unregistered"
  },
  {
    "id": "signal-health-core",
    "plane": "unregistered"
  },
  {
    "id": "source-quality",
    "plane": "unregistered"
  },
  {
    "id": "sql-guard-core",
    "plane": "unregistered"
  },
  {
    "id": "stream",
    "plane": "unregistered"
  },
  {
    "id": "trace",
    "plane": "unregistered"
  },
  {
    "id": "value-score-core",
    "plane": "unregistered"
  }
];

export const MAP_EDGES: MapEdge[] = [
  {
    "from": "app",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "admin-cookie",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "architecture",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "care-cookie",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "ccb-dossier-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "ccb-funnel",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "concordance-store",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "dose-limits",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "episode-state",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "episode-state",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "formulary",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "ipd-audit",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "ipd-audit",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "learning",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "learning-core",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "learning-flywheel-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "llm-cost",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "llm-cost-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "model-programme-core",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "observability-meta",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-cats",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-changelog",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-context-sort",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-doctor",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-doctor",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-audit-ui",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-case-anchor-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-feedback-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-feedback-ux-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-funnel-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-ingest-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-lvc-classify-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-note-audit",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "opd-note-score-core",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "reasoning",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "runs-export",
    "kind": "type"
  },
  {
    "from": "app/admin",
    "to": "runs-export",
    "kind": "value"
  },
  {
    "from": "app/admin",
    "to": "value-score-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "admin-cookie",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "admin-gate",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "appropriateness-runs",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "audit-suppression-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "audit-suppression-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "calculators",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "calculators",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "care-call-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "care-call-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "care-cookie",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "care-tracks",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "care-tracks-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-apikey",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-brief",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-brief-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-detect",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-dossier-cache",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-dossier-cache-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-episode-docs-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-fetch",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-fetch-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-resolve",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-search",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-search-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ccb-worklist-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "clinical-state",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "coach",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "concordance",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "concordance-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "concordance-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "curator",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ddi",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ddi-log",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ddi-reference",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ddx-constraints",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ddx-hypothesis",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "doc-audit",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "doc-audit-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "doctor-metrics-refresh",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "doctor-metrics-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "drugs",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "finding-match-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "formulary",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "gcp-auth",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "gemini-multimodal",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "gov-auth",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "harvest",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "harvest-epmc",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "inquiry",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "investigations",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "ipd-audit",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "lab",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "lab-batch",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "lab-batch-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "learning",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "learning-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "lvc",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "lvc-core",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "lvc-value",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "mcp-server",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "mcp-tools",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "med-audit",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "model-labels",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "multi-query",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-audit-doctor",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-audit-pdf",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-audit-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-audit-ui",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-complexity-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-feedback-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-gov-read",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-gov-signal-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-gov-signal-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-governance-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-ingest-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-longitudinal",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-lvc-classify-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-note-audit",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-note-audit-core",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-note-score-core",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "opd-triage-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "opd-triage-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "pathway",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "pathway-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "pharmacist-cookie",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "plos",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "proms",
    "kind": "type"
  },
  {
    "from": "app/api",
    "to": "proms",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "pubchem",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "reasoning",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "record-audit-link-store",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "rerank",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "review-queue-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "review-stats-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "right-care-state",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "signal-health-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "source-quality",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "sql-guard-core",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "stream",
    "kind": "value"
  },
  {
    "from": "app/api",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "app/appropriateness",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "app/appropriateness",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "app/appropriateness",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "app/appropriateness",
    "to": "lvc-value-core",
    "kind": "value"
  },
  {
    "from": "app/appropriateness",
    "to": "ndjson-client",
    "kind": "value"
  },
  {
    "from": "app/appropriateness",
    "to": "pathway-core",
    "kind": "type"
  },
  {
    "from": "app/appropriateness",
    "to": "record-audit-link-store",
    "kind": "type"
  },
  {
    "from": "app/appropriateness",
    "to": "runs-export",
    "kind": "value"
  },
  {
    "from": "app/ask",
    "to": "ndjson-client",
    "kind": "value"
  },
  {
    "from": "app/audit",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/audit",
    "to": "med-audit",
    "kind": "value"
  },
  {
    "from": "app/audit",
    "to": "pharmacist-cookie",
    "kind": "value"
  },
  {
    "from": "app/browse",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "care-cookie",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "ccb-brief-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "ccb-search",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "ccb-worklist-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "opd-feedback-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "opd-feedback-ux-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "review-navigator-core",
    "kind": "type"
  },
  {
    "from": "app/care",
    "to": "review-navigator-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "review-queue-core",
    "kind": "value"
  },
  {
    "from": "app/care",
    "to": "review-stats-core",
    "kind": "value"
  },
  {
    "from": "app/ddx",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "app/ddx",
    "to": "ndjson-client",
    "kind": "value"
  },
  {
    "from": "app/drugs",
    "to": "ndjson-client",
    "kind": "value"
  },
  {
    "from": "appropriateness-runs",
    "to": "clinical-state",
    "kind": "value"
  },
  {
    "from": "appropriateness-runs",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "audit-suppression-store",
    "to": "audit-suppression-core",
    "kind": "type"
  },
  {
    "from": "audit-suppression-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "audit-suppression-store",
    "to": "opd-audit-ui",
    "kind": "value"
  },
  {
    "from": "audit-suppression-store",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "audit-suppression-store",
    "to": "opd-triage-store",
    "kind": "value"
  },
  {
    "from": "care-call-core",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "care-call-core",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "care-call-store",
    "to": "care-call-core",
    "kind": "value"
  },
  {
    "from": "care-call-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "care-call-store",
    "to": "member-state",
    "kind": "type"
  },
  {
    "from": "care-call-store",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "care-tracks",
    "to": "care-tracks-core",
    "kind": "value"
  },
  {
    "from": "care-tracks",
    "to": "care-tracks-store",
    "kind": "value"
  },
  {
    "from": "care-tracks",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "care-tracks-store",
    "to": "care-tracks-core",
    "kind": "value"
  },
  {
    "from": "care-tracks-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "ccb-brief-core",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "ccb-extract-cache",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "ccb-fetch-core",
    "kind": "type"
  },
  {
    "from": "ccb-brief",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "gemini-multimodal",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "ccb-brief",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "ccb-brief-core",
    "to": "ccb-fetch-core",
    "kind": "type"
  },
  {
    "from": "ccb-brief-core",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "ccb-detect",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-dossier",
    "to": "ccb-dossier-core",
    "kind": "value"
  },
  {
    "from": "ccb-dossier",
    "to": "ccb-search-core",
    "kind": "value"
  },
  {
    "from": "ccb-dossier",
    "to": "ccb-timeline-enrich-core",
    "kind": "value"
  },
  {
    "from": "ccb-dossier",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-dossier-cache",
    "to": "ccb-dossier",
    "kind": "value"
  },
  {
    "from": "ccb-dossier-cache",
    "to": "ccb-dossier-cache-core",
    "kind": "value"
  },
  {
    "from": "ccb-dossier-cache",
    "to": "ccb-dossier-core",
    "kind": "type"
  },
  {
    "from": "ccb-dossier-cache",
    "to": "ccb-worklist-core",
    "kind": "value"
  },
  {
    "from": "ccb-dossier-cache",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ccb-dossier-cache-core",
    "to": "ccb-dossier-core",
    "kind": "type"
  },
  {
    "from": "ccb-episode-docs-core",
    "to": "ccb-fetch-core",
    "kind": "type"
  },
  {
    "from": "ccb-extract-cache",
    "to": "ccb-brief-core",
    "kind": "type"
  },
  {
    "from": "ccb-extract-cache",
    "to": "ccb-extract-cache-core",
    "kind": "value"
  },
  {
    "from": "ccb-extract-cache",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ccb-extract-cache-core",
    "to": "ccb-brief-core",
    "kind": "type"
  },
  {
    "from": "ccb-fetch",
    "to": "ccb-fetch-core",
    "kind": "value"
  },
  {
    "from": "ccb-fetch",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-fetch",
    "to": "opd-ingest-core",
    "kind": "value"
  },
  {
    "from": "ccb-fetch-core",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "ccb-funnel",
    "to": "ccb-brief-core",
    "kind": "value"
  },
  {
    "from": "ccb-funnel",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ccb-funnel",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-resolve",
    "to": "ccb-search",
    "kind": "value"
  },
  {
    "from": "ccb-resolve",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-search",
    "to": "ccb-search-core",
    "kind": "value"
  },
  {
    "from": "ccb-search",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ccb-store",
    "to": "ccb-brief-core",
    "kind": "type"
  },
  {
    "from": "ccb-store",
    "to": "ccb-fetch-core",
    "kind": "type"
  },
  {
    "from": "ccb-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ccb-timeline-enrich-core",
    "to": "ccb-dossier-core",
    "kind": "type"
  },
  {
    "from": "charge-master",
    "to": "charge-master-core",
    "kind": "type"
  },
  {
    "from": "charge-master",
    "to": "charge-master-core",
    "kind": "value"
  },
  {
    "from": "clinical-state",
    "to": "ccb-dossier-core",
    "kind": "type"
  },
  {
    "from": "clinical-state",
    "to": "ccb-dossier-core",
    "kind": "value"
  },
  {
    "from": "clinical-state",
    "to": "concordance-core",
    "kind": "value"
  },
  {
    "from": "clinical-state",
    "to": "ddx-eval-core",
    "kind": "value"
  },
  {
    "from": "clinical-state",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "clinical-state",
    "to": "investigations",
    "kind": "type"
  },
  {
    "from": "coach",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "coach",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "concordance",
    "to": "concordance-core",
    "kind": "value"
  },
  {
    "from": "concordance",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "concordance",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "concordance-store",
    "to": "concordance-core",
    "kind": "type"
  },
  {
    "from": "concordance-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "curator",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "curator",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "curator",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "ddi",
    "to": "ddi-tags",
    "kind": "value"
  },
  {
    "from": "ddi",
    "to": "rxlabelguard",
    "kind": "value"
  },
  {
    "from": "ddi-log",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ddi-log",
    "to": "rxlabelguard",
    "kind": "type"
  },
  {
    "from": "ddi-reference",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ddi-reference",
    "to": "rxlabelguard",
    "kind": "type"
  },
  {
    "from": "ddi-tags",
    "to": "ddi",
    "kind": "type"
  },
  {
    "from": "ddi-tags",
    "to": "rxlabelguard",
    "kind": "type"
  },
  {
    "from": "ddx-hypothesis",
    "to": "retrieve",
    "kind": "type"
  },
  {
    "from": "ddx-hypothesis",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "ddx-hypothesis",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "charge-master",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "doc-audit",
    "to": "doc-audit-core",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "gemini-multimodal",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "lvc-value-core",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "pathway",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "prognosis-core",
    "kind": "type"
  },
  {
    "from": "doc-audit",
    "to": "prognosis-core",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "record-audit-link-store",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "room-rent",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "doc-audit",
    "to": "value-score-core",
    "kind": "value"
  },
  {
    "from": "doc-audit-core",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "doc-audit-core",
    "to": "lvc-value-core",
    "kind": "type"
  },
  {
    "from": "doc-audit-core",
    "to": "pathway-core",
    "kind": "type"
  },
  {
    "from": "doc-audit-core",
    "to": "prognosis-core",
    "kind": "type"
  },
  {
    "from": "doc-audit-core",
    "to": "value-score-core",
    "kind": "type"
  },
  {
    "from": "doctor-metrics-refresh",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "doctor-metrics-refresh",
    "to": "doctor-directory-core",
    "kind": "value"
  },
  {
    "from": "doctor-metrics-refresh",
    "to": "doctor-metrics-store",
    "kind": "value"
  },
  {
    "from": "doctor-metrics-refresh",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "doctor-metrics-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "doctor-metrics-store",
    "to": "doctor-directory-core",
    "kind": "type"
  },
  {
    "from": "dose-aggregation-core",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "dose-aggregation-core",
    "to": "opd-note-audit-core",
    "kind": "type"
  },
  {
    "from": "dose-limits",
    "to": "dose-aggregation-core",
    "kind": "value"
  },
  {
    "from": "dose-limits",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "dose-limits",
    "to": "opd-note-audit-core",
    "kind": "type"
  },
  {
    "from": "drugs",
    "to": "pubchem",
    "kind": "value"
  },
  {
    "from": "drugs",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "episode-state",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "episode-state",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "expand",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "expand",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "formulary",
    "to": "formulary-match-core",
    "kind": "value"
  },
  {
    "from": "formulary",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "gemini-multimodal",
    "to": "gcp-auth",
    "kind": "value"
  },
  {
    "from": "gemini-multimodal",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "gemini-multimodal",
    "to": "llm-cost-core",
    "kind": "value"
  },
  {
    "from": "gemini-multimodal",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "harvest",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "harvest",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "harvest",
    "to": "pubmed",
    "kind": "value"
  },
  {
    "from": "harvest-epmc",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "harvest-epmc",
    "to": "europepmc",
    "kind": "value"
  },
  {
    "from": "harvest-epmc",
    "to": "jats-chunk",
    "kind": "value"
  },
  {
    "from": "harvest-epmc",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "inquiry",
    "to": "care-call-core",
    "kind": "type"
  },
  {
    "from": "inquiry",
    "to": "care-call-core",
    "kind": "value"
  },
  {
    "from": "inquiry",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "inquiry",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "inquiry",
    "to": "member-state",
    "kind": "type"
  },
  {
    "from": "inquiry",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "inquiry",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "investigations",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "doc-audit",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "ipd-audit",
    "to": "episode-state",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "gcp-auth",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "ipd-audit",
    "to": "value-score-core",
    "kind": "type"
  },
  {
    "from": "lab",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "lab",
    "to": "lab-core",
    "kind": "value"
  },
  {
    "from": "lab",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "lab",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "lab-batch-core",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "lab-batch",
    "to": "opd-note-audit",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "audit-suppression-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "audit-suppression-store",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "learning-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "learning-flywheel-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "model-programme-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "review-stats-core",
    "kind": "value"
  },
  {
    "from": "learning",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "llm",
    "to": "gcp-auth",
    "kind": "value"
  },
  {
    "from": "llm-cost",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "llm-cost",
    "to": "llm-cost-core",
    "kind": "value"
  },
  {
    "from": "lvc",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "lvc",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "lvc",
    "to": "lvc-core",
    "kind": "type"
  },
  {
    "from": "lvc",
    "to": "lvc-core",
    "kind": "value"
  },
  {
    "from": "lvc",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "lvc",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "charge-master",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "lvc-value",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "lvc-value-core",
    "kind": "type"
  },
  {
    "from": "lvc-value",
    "to": "lvc-value-core",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "lvc-value",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "lvc-value-core",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "mcp-server",
    "to": "mcp-tools",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "lab",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "lab-batch",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "lab-batch-core",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "lab-clinical-core",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "mini-backfill",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "opd-audit-store",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "opd-feedback-rollup-core",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "opd-note-audit",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "sql-guard-core",
    "kind": "value"
  },
  {
    "from": "mcp-tools",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "as-of-core",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "care-call-core",
    "kind": "type"
  },
  {
    "from": "member-state",
    "to": "care-call-store",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "ccb-dossier-core",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "member-state",
    "to": "clinical-state",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "member-state",
    "to": "proms",
    "kind": "value"
  },
  {
    "from": "metabase",
    "to": "opd-complexity-core",
    "kind": "value"
  },
  {
    "from": "mini-backfill",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "multi-query",
    "to": "db",
    "kind": "type"
  },
  {
    "from": "multi-query",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "multi-query",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "multi-query",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "opd-audit-doctor",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-audit-doctor",
    "to": "opd-funnel-core",
    "kind": "type"
  },
  {
    "from": "opd-audit-doctor",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "opd-audit-store",
    "to": "clinical-state",
    "kind": "value"
  },
  {
    "from": "opd-audit-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-audit-store",
    "to": "opd-longitudinal",
    "kind": "value"
  },
  {
    "from": "opd-audit-store",
    "to": "opd-note-audit",
    "kind": "type"
  },
  {
    "from": "opd-audit-store",
    "to": "opd-note-score-core",
    "kind": "type"
  },
  {
    "from": "opd-audit-store",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "opd-gov-read",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "opd-gov-read",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-gov-read",
    "to": "opd-audit-ui",
    "kind": "value"
  },
  {
    "from": "opd-gov-read",
    "to": "opd-gov-signal-core",
    "kind": "type"
  },
  {
    "from": "opd-gov-read",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "opd-gov-signal-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-gov-signal-store",
    "to": "opd-gov-signal-core",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "audit-suppression-core",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "audit-suppression-store",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "member-state",
    "kind": "type"
  },
  {
    "from": "opd-longitudinal",
    "to": "member-state",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "opd-longitudinal",
    "to": "opd-note-audit",
    "kind": "type"
  },
  {
    "from": "opd-longitudinal",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "opd-triage-core",
    "kind": "value"
  },
  {
    "from": "opd-longitudinal",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "audit-suppression-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "audit-suppression-store",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "ddi",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "ddi-tags",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "dose-limits",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "formulary",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-complexity-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-ingest-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-longitudinal",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-lvc-classify-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-note-audit-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "opd-note-score-core",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "opd-note-audit",
    "to": "rxlabelguard",
    "kind": "type"
  },
  {
    "from": "opd-note-audit",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "opd-note-audit-core",
    "to": "opd-ingest-core",
    "kind": "type"
  },
  {
    "from": "opd-note-audit-core",
    "to": "opd-note-score-core",
    "kind": "type"
  },
  {
    "from": "opd-note-score-core",
    "to": "value-score-core",
    "kind": "type"
  },
  {
    "from": "opd-triage-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "opd-triage-store",
    "to": "opd-gov-signal-store",
    "kind": "value"
  },
  {
    "from": "opd-triage-store",
    "to": "opd-triage-core",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "charge-master",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "citations-core",
    "kind": "type"
  },
  {
    "from": "pathway",
    "to": "citations-core",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "lvc-value-core",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "pathway-core",
    "kind": "type"
  },
  {
    "from": "pathway",
    "to": "pathway-core",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "retrieve",
    "kind": "value"
  },
  {
    "from": "pathway",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "pathway-core",
    "to": "lvc-value-core",
    "kind": "type"
  },
  {
    "from": "proms",
    "to": "clinical-state",
    "kind": "type"
  },
  {
    "from": "proms",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "proms",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "proms",
    "to": "member-state",
    "kind": "type"
  },
  {
    "from": "proms",
    "to": "metabase",
    "kind": "value"
  },
  {
    "from": "proms",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "record-audit-link-store",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "rerank",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "rerank",
    "to": "trace",
    "kind": "value"
  },
  {
    "from": "retrieve",
    "to": "db",
    "kind": "type"
  },
  {
    "from": "retrieve",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "retrieve",
    "to": "expand",
    "kind": "value"
  },
  {
    "from": "retrieve",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "retrieve",
    "to": "rerank",
    "kind": "value"
  },
  {
    "from": "retrieve",
    "to": "source-quality",
    "kind": "value"
  },
  {
    "from": "review-stats-core",
    "to": "review-queue-core",
    "kind": "value"
  },
  {
    "from": "right-care-ground-eval-core",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "right-care-ground-eval-core",
    "to": "lvc-core",
    "kind": "type"
  },
  {
    "from": "right-care-ground-eval-core",
    "to": "pathway-core",
    "kind": "type"
  },
  {
    "from": "right-care-state",
    "to": "appropriateness-runs",
    "kind": "type"
  },
  {
    "from": "right-care-state",
    "to": "clinical-state",
    "kind": "value"
  },
  {
    "from": "right-care-state",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "room-rent",
    "to": "doc-audit-core",
    "kind": "type"
  },
  {
    "from": "room-rent",
    "to": "room-rent-core",
    "kind": "value"
  },
  {
    "from": "trace",
    "to": "db",
    "kind": "value"
  },
  {
    "from": "trace",
    "to": "llm",
    "kind": "value"
  },
  {
    "from": "trace",
    "to": "llm-cost-core",
    "kind": "value"
  },
  {
    "from": "trace",
    "to": "reasoning",
    "kind": "value"
  },
  {
    "from": "value-score-core",
    "to": "doc-audit-core",
    "kind": "type"
  }
];

export const VERSION_REGISTRY: VersionRow[] = [
  {
    "constName": "ADHOC_GEN_VERSION",
    "value": "adhoc-gen/0.1",
    "file": "lib/proms/adhoc-core.ts",
    "derived": false
  },
  {
    "constName": "ASK_SET_VERSION",
    "value": "ask-set/0.1",
    "file": "lib/care-call-core.ts",
    "derived": false
  },
  {
    "constName": "CCB_ENGINE_VERSION",
    "value": "care-brief/0.1",
    "file": "lib/ccb-brief-core.ts",
    "derived": false
  },
  {
    "constName": "CLINICAL_STATE_VERSION",
    "value": "clinical-state/1.2",
    "file": "lib/clinical-state/schema.ts",
    "derived": false
  },
  {
    "constName": "DOSE_LIMITS_VERSION",
    "value": "TABLE.version",
    "file": "lib/dose-limits.ts",
    "derived": true
  },
  {
    "constName": "EPISODE_STATE_VERSION",
    "value": "episode-state/0.1",
    "file": "lib/episode-state/schema.ts",
    "derived": false
  },
  {
    "constName": "EXTRACTION_EVAL_VERSION",
    "value": "clinical-state-extraction-eval/2",
    "file": "lib/clinical-state/extraction-eval-core.ts",
    "derived": false
  },
  {
    "constName": "HS_SETS_VERSION",
    "value": "hs-sets/0.2",
    "file": "lib/proms/catalog.ts",
    "derived": false
  },
  {
    "constName": "ICD_MASTER_VERSION",
    "value": "icd-master/1.0",
    "file": "lib/member-state/icd-master.generated.ts",
    "derived": false
  },
  {
    "constName": "INQUIRY_ASK_SET_VERSION",
    "value": "ask-set/0.2",
    "file": "lib/inquiry/inquiry-core.ts",
    "derived": false
  },
  {
    "constName": "INQUIRY_EVAL_VERSION",
    "value": "inquiry-eval/1.0",
    "file": "lib/inquiry/inquiry-eval-core.ts",
    "derived": false
  },
  {
    "constName": "INQUIRY_GOLD_VERSION",
    "value": "inquiry-gold/1.0",
    "file": "lib/inquiry/inquiry-eval-core.ts",
    "derived": false
  },
  {
    "constName": "INQUIRY_VERSION",
    "value": "inquiry/0.1",
    "file": "lib/inquiry/inquiry-core.ts",
    "derived": false
  },
  {
    "constName": "IPD_AUDIT_GOLD_VERSION",
    "value": "ipd-audit-gold/1.1",
    "file": "lib/ipd-audit/gold.ts",
    "derived": false
  },
  {
    "constName": "IPD_ENGINE_VERSION",
    "value": "ipd-discharge-audit/0.1",
    "file": "lib/ipd-audit/store.ts",
    "derived": false
  },
  {
    "constName": "IPD_MINI_ENGINE_VERSION",
    "value": "`${IPD_ENGINE_VERSION}-mini`",
    "file": "lib/ipd-audit/store.ts",
    "derived": true
  },
  {
    "constName": "MATCHER_VERSION",
    "value": "ddx-eval/3",
    "file": "lib/ddx-eval-core.ts",
    "derived": false
  },
  {
    "constName": "MCP_PROTOCOL_VERSION",
    "value": "2024-11-05",
    "file": "lib/mcp-server.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_BANK_VERSION",
    "value": "member-bank/1.0",
    "file": "lib/member-state/validation/gold-seed.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_EVAL_VERSION",
    "value": "member-eval/0.1",
    "file": "lib/member-state/validation/score-core.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_PRESENT_VERSION",
    "value": "member-present/0.2",
    "file": "lib/member-state/present-augment.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_RECONCILE_VERSION",
    "value": "member-reconcile/0.3",
    "file": "lib/member-state/aggregate-core.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_STATE_PRESENT_VERSION",
    "value": "member-state-present/0.1",
    "file": "lib/member-state/present-core.ts",
    "derived": false
  },
  {
    "constName": "MEMBER_STATE_VERSION",
    "value": "member-state/1.1",
    "file": "lib/member-state/schema.ts",
    "derived": false
  },
  {
    "constName": "NORMALIZATION_VERSION",
    "value": "member-norm/0.1",
    "file": "lib/member-state/schema.ts",
    "derived": false
  },
  {
    "constName": "OPD_ENGINE_VERSION",
    "value": "opd-note-audit/0.81.8",
    "file": "lib/opd-note-audit-core.ts",
    "derived": false
  },
  {
    "constName": "OPD_ENGINE_VERSIONS_CURRENT",
    "value": "['opd-note-audit/0.81.3', 'opd-note-audit/0.81.4', 'opd-note-audit/0.81.5', 'opd-note-audit/0.81.6', 'opd-note-audit/0.81.7', 'opd-note-audit/0.81.8']",
    "file": "lib/opd-note-audit-core.ts",
    "derived": true
  },
  {
    "constName": "OPD_LONGITUDINAL_VERSION",
    "value": "opd-longitudinal/0.1",
    "file": "lib/opd-longitudinal-core.ts",
    "derived": false
  },
  {
    "constName": "OPD_MINI_ENGINE_VERSION",
    "value": "`${OPD_ENGINE_VERSION}-mini`",
    "file": "lib/opd-note-audit.ts",
    "derived": true
  },
  {
    "constName": "PROM_CATALOG_VERSION",
    "value": "prom-catalog/0.1",
    "file": "lib/proms/catalog.ts",
    "derived": false
  },
  {
    "constName": "PROM_ITEM_BANK_VERSION",
    "value": "prom-item-bank/0.1",
    "file": "lib/proms/item-bank-core.ts",
    "derived": false
  },
  {
    "constName": "PROM_SCHED_VERSION",
    "value": "prom-sched/0.1",
    "file": "lib/proms/schedule-core.ts",
    "derived": false
  },
  {
    "constName": "PROM_SCORING_VERSION",
    "value": "prom-scoring/0.1",
    "file": "lib/proms/schedule-core.ts",
    "derived": false
  },
  {
    "constName": "PX_ENGINE_VERSION",
    "value": "prognosis/0.1",
    "file": "lib/prognosis-core.ts",
    "derived": false
  },
  {
    "constName": "RECONCILIATION_VERSION",
    "value": "member-reconcile/0.2",
    "file": "lib/member-state/schema.ts",
    "derived": false
  },
  {
    "constName": "RIGHT_CARE_CHECK_GOLD_2_VERSION",
    "value": "right-care-check-gold/2.0",
    "file": "lib/right-care-ground-eval-core.ts",
    "derived": false
  },
  {
    "constName": "RIGHT_CARE_CHECK_GOLD_VERSION",
    "value": "right-care-check-gold/1.0",
    "file": "lib/right-care-ground-eval-core.ts",
    "derived": false
  },
  {
    "constName": "RIGHT_CARE_GROUND_EVAL_VERSION",
    "value": "right-care-ground-eval/1.0",
    "file": "lib/right-care-ground-eval-core.ts",
    "derived": false
  },
  {
    "constName": "SNAPSHOT_SCHEMA_VERSION",
    "value": "2",
    "file": "lib/ccb-dossier-cache-core.ts",
    "derived": false
  }
];

export const COVERAGE = {
  "registered": 12,
  "unregistered": 15,
  "total": 27,
  "unregisteredIds": [
    "calculators",
    "care-call-core",
    "ccb-brief-core",
    "ccb-dossier-cache-core",
    "ddx-eval-core",
    "doc-audit-core",
    "dose-limits",
    "formulary-match-core",
    "mcp-server",
    "opd-note-audit",
    "opd-note-audit-core",
    "prognosis-core",
    "proms",
    "reasoning",
    "right-care-ground-eval-core"
  ]
} as const;

export const MAP_RULES: MapRule[] = [
  {
    "id": 1,
    "name": "pure clinical cores must not reach up into the app",
    "sourceGlobs": [
      "lib/clinical-state/**",
      "lib/member-state/**",
      "lib/opd-note-score-core.ts",
      "lib/opd-longitudinal-core.ts"
    ]
  },
  {
    "id": 2,
    "name": "advisory must not import score arithmetic (finding types/identity from opd-note-audit-core ARE allowed)",
    "sourceGlobs": [
      "lib/opd-longitudinal*",
      "lib/opd-triage-core.ts"
    ]
  },
  {
    "id": 3,
    "name": "the spine runs no audit/score logic (VALUE imports; `import type` is allowed)",
    "sourceGlobs": [
      "lib/member-state/**",
      "lib/clinical-state/**"
    ]
  },
  {
    "id": 4,
    "name": "the spine must not couple to a prediction layer",
    "sourceGlobs": [
      "lib/member-state/**",
      "lib/clinical-state/**"
    ]
  },
  {
    "id": 5,
    "name": "inquiry (advisory) and the scored cores never value-import each other",
    "sourceGlobs": [
      "lib/inquiry/**",
      "lib/opd-note-audit-core.ts",
      "lib/opd-note-score-core.ts",
      "lib/doc-audit-core.ts",
      "lib/formulary-match-core.ts"
    ]
  },
  {
    "id": 6,
    "name": "the spine must not value-import the IPD audit module",
    "sourceGlobs": [
      "lib/member-state/**",
      "lib/clinical-state/**"
    ]
  },
  {
    "id": 7,
    "name": "the frozen spine must not import EpisodeState",
    "sourceGlobs": [
      "lib/member-state/**",
      "lib/clinical-state/**"
    ]
  }
];

export const GENERATED_FROM = {
  "scanned": [
    "lib/** (tests excluded)",
    "app/** (boundary edges into lib/ only)"
  ],
  "sources": [
    "import scan: scripts/lib/import-scan.mjs",
    "planes: lib/architecture/manifests.ts",
    "rules: scripts/architecture-check.mjs"
  ],
  "command": "npm run architecture:map"
} as const;
