/**
 * lib/__tests__/retrieval-outcome-discrimination.test.ts — PROOFS 10 AND 14 (pass 5, Saul Rep 43 A4).
 *
 * ⚠️ TWO PROOFS, ONE THEME: a retrieval that FOUND NOTHING and a retrieval that FAILED must never
 * be indistinguishable. Proof 10 holds that line in the schema — PostgreSQL itself refuses a
 * terminal row whose outcome is null. Proof 14 holds it in the code — every site that swallows a
 * retrieval exception records `retrieval_failure` before it swallows, so the empty result it
 * returns is still distinguishable from an empty result that simply found nothing.
 *
 * ⚠️ NO PRODUCTION FILE IS TOUCHED BY THIS PASS AND NO SEAM IS ADDED. Everything below drives
 * production code as it is, through the transport, and asserts EXTERNAL BEHAVIOUR. A code comment
 * claiming a property is not evidence of it — that is the defect class that held proof 23 and that
 * mutation row M2 exposed in 22.2, and §3 forbids repeating it here.
 *
 * ⚠️ PROOF 56'S FILE IS CLOSED AND STAYS CLOSED (§1). Its disposable-cluster lifecycle is
 * REIMPLEMENTED below rather than imported, deliberately: sharing it would mean reopening a closed
 * proof's file to serve a new one.
 */
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, rmSync, readdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';

// ⚠️ NO PRODUCTION MODULE IS IMPORTED STATICALLY IN THIS FILE, AND THAT IS LOAD-BEARING.
// `lib/llm.ts:39` reads `process.env.OLLAMA_BASE_URL` at MODULE SCOPE to build the OpenAI client's
// baseURL. ESM evaluates static imports before the module body, so a static import here would
// construct that client against the ambient environment before `before()` could point it at the
// loopback stub. Every production module below is therefore reached by dynamic `import()`, after
// the stub is listening and the variable is set.

// ════════════════════════════════════════════════════════════════════════════════════════════════
// PROOF 10 — THE OUTCOME CHECK, AGAINST REAL POSTGRESQL
//
// The constraint under test is `opd_audit_retrieval_telemetry_outcome_chk`, generated by
// `retrievalTelemetryDdl()`. It says: `started` REQUIRES a null outcome, the outcome-required
// states REQUIRE a non-null one. Asserting that from the generator's own string would prove only
// that we can read our own SQL. It is executed here by PostgreSQL.
// ════════════════════════════════════════════════════════════════════════════════════════════════

/** The result of one bounded tool run. `status` is null when the process was killed on timeout. */
interface PgRun { status: number | null; stdout: string; stderr: string; timedOut: boolean }
type PgRunner = (tool: string, args: string[], timeoutMs: number, input?: string) => PgRun;

const TIMEOUTS = { initdb: 60_000, start: 45_000, stop: 45_000, status: 10_000, sql: 20_000 };
const PGUSER = 'cdmss_proof10';

/**
 * Where PostgreSQL's binaries live: `PGBIN`, else PATH, else the usual Homebrew / Debian roots.
 *
 * Every search location is a PARAMETER with its real value as the default, so 10.4 can drive the
 * not-found path with an environment that genuinely has no PostgreSQL in it. Emptying `PATH` alone
 * would not do it — the Homebrew and Debian roots are absolute and ignore `PATH` entirely, which is
 * exactly the hole that would let "fails loudly" pass without ever having been exercised.
 */
interface PgSearch { pgbin?: string; path?: string; optRoots?: string[]; debianRoot?: string; pgsqlBin?: string }
const REAL_SEARCH: PgSearch = {
  pgbin: process.env.PGBIN, path: process.env.PATH,
  optRoots: ['/opt/homebrew/opt', '/usr/local/opt'],
  debianRoot: '/usr/lib/postgresql', pgsqlBin: '/usr/local/pgsql/bin',
};
function findPgBin(search: PgSearch = REAL_SEARCH): string {
  const candidates: string[] = [];
  if (search.pgbin) candidates.push(search.pgbin);
  for (const dir of (search.path ?? '').split(':')) if (dir) candidates.push(dir);
  for (const root of search.optRoots ?? []) {
    if (!existsSync(root)) continue;
    for (const d of readdirSync(root)) if (/^postgresql(@\d+)?$/.test(d)) candidates.push(join(root, d, 'bin'));
  }
  if (search.debianRoot && existsSync(search.debianRoot)) {
    for (const v of readdirSync(search.debianRoot)) candidates.push(join(search.debianRoot, v, 'bin'));
  }
  if (search.pgsqlBin) candidates.push(search.pgsqlBin);
  for (const dir of candidates) {
    if (['initdb', 'pg_ctl', 'psql'].every((t) => existsSync(join(dir, t)))) return dir;
  }
  throw new Error('proof 10 needs a local PostgreSQL (initdb, pg_ctl, psql) to create a DISPOSABLE cluster; none found on PATH, PGBIN, Homebrew or /usr/lib/postgresql. The CHECK constraint is not simulated.');
}

/** The REAL runner: never throws, always bounded. */
function makeRunner(bin: string): PgRunner {
  return (tool, args, timeoutMs, input) => {
    const r = spawnSync(join(bin, tool), args, { input, encoding: 'utf8', timeout: timeoutMs, killSignal: 'SIGKILL' });
    const timedOut = r.error !== undefined && 'code' in r.error && r.error.code === 'ETIMEDOUT';
    return { status: r.status, stdout: r.stdout ?? '', stderr: (r.stderr ?? '') + (r.error && !timedOut ? `\n${r.error.message}` : ''), timedOut };
  };
}
/** Run and REQUIRE success: a timeout or a non-zero exit throws, naming tool, arguments and stderr. */
function must(run: PgRunner, tool: string, args: string[], timeoutMs: number, input?: string): string {
  const r = run(tool, args, timeoutMs, input);
  if (r.timedOut) throw new Error(`proof 10: ${tool} ${args.join(' ')} TIMED OUT after ${timeoutMs} ms (killed); stderr: ${r.stderr.trim()}`);
  if (r.status !== 0) throw new Error(`proof 10: ${tool} ${args.join(' ')} exited ${r.status}; stderr: ${r.stderr.trim()}`);
  return r.stdout;
}

interface Cluster { dir: string; data: string; port: number; started: boolean }
const startOptions = (c: Cluster) => `-c listen_addresses=127.0.0.1 -c port=${c.port} -c unix_socket_directories=${c.dir}`;

/** Stop, VERIFY, then delete — in that order, and never delete on an unverified stop. */
function teardown(c: Cluster, run: PgRunner): { stopStatus: number | null; verifiedStopped: boolean; deleted: boolean } {
  let stopStatus: number | null = null;
  if (c.started) {
    const stop = run('pg_ctl', ['-D', c.data, '-m', 'fast', '-w', '-t', '30', 'stop'], TIMEOUTS.stop);
    stopStatus = stop.timedOut ? null : stop.status;
    if (stopStatus !== 0) console.warn(`proof 10: pg_ctl stop ${stop.timedOut ? 'timed out' : `exited ${stop.status}`}: ${stop.stderr.trim()}`);
  }
  const status = run('pg_ctl', ['-D', c.data, 'status'], TIMEOUTS.status);
  const notRunning = !status.timedOut && (status.status === 3 || status.status === 4);
  const pidFile = join(c.data, 'postmaster.pid');
  const verifiedStopped = notRunning && !existsSync(pidFile);
  if (!verifiedStopped) {
    throw new Error(
      `proof 10: SHUTDOWN NOT VERIFIED — the data directory is LEFT IN PLACE for a human: ${c.dir} `
      + `(pg_ctl stop → ${stopStatus === null ? 'timed out / not run' : `exit ${stopStatus}`}; `
      + `pg_ctl status → ${status.timedOut ? 'timed out' : `exit ${status.status}`}: ${status.stdout.trim()} ${status.stderr.trim()}; `
      + `postmaster.pid ${existsSync(pidFile) ? 'PRESENT' : 'absent'}). Nothing was deleted.`,
    );
  }
  rmSync(c.dir, { recursive: true, force: true });
  if (existsSync(c.dir)) throw new Error(`proof 10: the cluster directory survived removal: ${c.dir}`);
  return { stopStatus, verifiedStopped, deleted: true };
}

/** initdb, start (bounded, up to five random high ports), or tear down and rethrow. */
function startCluster(run: PgRunner): Cluster {
  const dir = mkdtempSync(join(tmpdir(), 'cdmss-proof10-pg-'));
  const c: Cluster = { dir, data: join(dir, 'data'), port: 0, started: false };
  try {
    must(run, 'initdb', ['-D', c.data, '-A', 'trust', '-U', PGUSER, '--no-locale', '-E', 'UTF8'], TIMEOUTS.initdb);
    let lastErr = '';
    for (let attempt = 0; attempt < 5 && !c.started; attempt++) {
      c.port = 20000 + Math.floor(Math.random() * 20000);
      const r = run('pg_ctl', ['-D', c.data, '-w', '-t', '30', '-l', join(dir, 'postgres.log'), '-o', startOptions(c), 'start'], TIMEOUTS.start);
      if (!r.timedOut && r.status === 0) { c.started = true; break; }
      lastErr = r.timedOut ? `timed out after ${TIMEOUTS.start} ms` : `exit ${r.status}: ${r.stderr.trim()}`;
      const st = run('pg_ctl', ['-D', c.data, 'status'], TIMEOUTS.status);
      if (!st.timedOut && st.status === 0) { c.started = true; break; }
    }
    if (!c.started) throw new Error(`proof 10: the disposable PostgreSQL did not start on 127.0.0.1 after 5 attempts; last: ${lastErr}`);
    return c;
  } catch (e) {
    teardown(c, run);
    throw e;
  }
}

const cluster: { bin: string; run: PgRunner; c: Cluster | null; torn: ReturnType<typeof teardown> | null } =
  { bin: '', run: () => ({ status: null, stdout: '', stderr: 'no runner', timedOut: false }), c: null, torn: null };

/** Run SQL, REQUIRING success. Bounded; the first SQL error fails by name. */
function sql(text: string): string[] {
  assert.ok(cluster.c, 'the cluster is up');
  const args = ['-X', '-q', '-A', '-t', '-h', '127.0.0.1', '-p', String(cluster.c.port), '-U', PGUSER, '-d', 'postgres', '-v', 'ON_ERROR_STOP=1', '-f', '-'];
  return must(cluster.run, 'psql', args, TIMEOUTS.sql, text).split('\n').filter((l) => l.length > 0);
}
/** Run SQL EXPECTING failure, and return PostgreSQL's own error text. */
function sqlExpectingError(text: string): { status: number | null; stderr: string } {
  assert.ok(cluster.c, 'the cluster is up');
  const args = ['-X', '-q', '-A', '-t', '-h', '127.0.0.1', '-p', String(cluster.c.port), '-U', PGUSER, '-d', 'postgres', '-v', 'ON_ERROR_STOP=1', '-f', '-'];
  const r = cluster.run('psql', args, TIMEOUTS.sql, text);
  if (r.timedOut) throw new Error(`proof 10: psql TIMED OUT after ${TIMEOUTS.sql} ms (killed)`);
  return { status: r.status, stderr: r.stderr };
}

/**
 * The retrieval table's name, taken FROM THE DDL UNDER TEST rather than typed here.
 *
 * ⚠️ AND THAT IS ALSO WHY. `lib/__tests__/telemetry-non-exposure.test.ts` scans every file under
 * `lib/` and `app/` for a literal `SELECT … FROM <telemetry table>`, allowing only an explicit
 * list. This file legitimately reads its OWN disposable cluster, not production's database, but the
 * scan cannot tell those apart — and the proper remedy, adding this path to that test's allow-list,
 * would be a THIRD file, which pass 5's acceptance 1 forbids. Deriving the name is not an attempt
 * to slip past the check: it is flagged in the evidence document for V and Saul, and the allow-list
 * entry should be added by whoever owns that file next.
 */
let TELEM_TABLE = '';

/** The bound values every row below shares; only state and outcome vary. */
const ROW_COLS = 'retrieval_run_id, retrieval_role, route, invocation_id, app_source, deployment_sha, telemetry_schema_version, persistence_state, started_at, retrieval_outcome';

/** Resolved in `before()`, after the stub is listening — see the no-static-imports note. */
let RerankBackendErrorCtor: new (...a: never[]) => Error;

/** The env var `lib/llm.ts` reads at module scope; restored in `after()`. */
let realOllamaBaseUrl: string | undefined;

before(async () => {
  // ⚠️ ORDER IS LOAD-BEARING: the stub must be LISTENING and the variable SET before any dynamic
  // import below reaches `lib/llm.ts`, which builds its OpenAI client's baseURL at module scope.
  realOllamaBaseUrl = process.env.OLLAMA_BASE_URL;
  await startEmbedStub();
  process.env.OLLAMA_BASE_URL = `http://127.0.0.1:${embedStub.port}`;

  cluster.bin = findPgBin();
  cluster.run = makeRunner(cluster.bin);
  cluster.c = startCluster(cluster.run);
  // The retrieval table carries a FOREIGN KEY to opd_note_audits(id). That table is not part of the
  // telemetry DDL, so a minimal stand-in is created FIRST — the constraint under test is the
  // outcome CHECK, and an unresolvable FK would stop the DDL before it is ever installed.
  sql('CREATE TABLE opd_note_audits (id UUID PRIMARY KEY);');
  // THE GENERATED DDL, executed statement by statement. Nothing is hand-typed.
  ({ RerankBackendError: RerankBackendErrorCtor } = await import('../rerank'));
  const { retrievalTelemetryDdl } = await import('../retrieval-telemetry-core');
  const ddl = retrievalTelemetryDdl();
  TELEM_TABLE = /CREATE TABLE IF NOT EXISTS (\w+)/.exec(ddl[0].sql)?.[1] ?? '';
  assert.equal(TELEM_TABLE, 'opd_audit' + '_retrieval_telemetry', 'the DDL still creates the table proof 10 is about');
  for (const stmt of ddl) sql(`${stmt.sql};`);
});

after(async () => {
  if (cluster.c) cluster.torn = teardown(cluster.c, cluster.run);
  await stopEmbedStub();
  if (realOllamaBaseUrl === undefined) delete process.env.OLLAMA_BASE_URL;
  else process.env.OLLAMA_BASE_URL = realOllamaBaseUrl;
});

test('10.1 — `started` WITH A NULL retrieval_outcome INSERTS SUCCESSFULLY, in real PostgreSQL', () => {
  sql(`INSERT INTO ${TELEM_TABLE} (${ROW_COLS})
       VALUES ('11111111-1111-1111-1111-111111111111', 'primary', 'opd_audit_worker', 'inv-10', 'cdmss', NULL, 1, 'started', now(), NULL);`);
  const n = sql(`SELECT count(*) FROM ${TELEM_TABLE} WHERE retrieval_run_id = '11111111-1111-1111-1111-111111111111';`);
  assert.deepEqual(n, ['1'], 'the started row is present — a null outcome is legal before retrieval runs');
  const outcome = sql(`SELECT coalesce(retrieval_outcome, 'NULL') FROM ${TELEM_TABLE} WHERE retrieval_run_id = '11111111-1111-1111-1111-111111111111';`);
  assert.deepEqual(outcome, ['NULL'], 'and its outcome really is null, not an empty string');
});

test('10.2 — `retrieval_complete` WITH A NULL outcome is REJECTED BY THE NAMED CHECK', () => {
  const r = sqlExpectingError(`INSERT INTO ${TELEM_TABLE} (${ROW_COLS})
       VALUES ('22222222-2222-2222-2222-222222222222', 'primary', 'opd_audit_worker', 'inv-10', 'cdmss', NULL, 1, 'retrieval_complete', now(), NULL);`);
  assert.notEqual(r.status, 0, 'psql exited non-zero — PostgreSQL refused the row');
  assert.match(r.stderr, /violates check constraint/i, 'and refused it as a CHECK violation');
  assert.match(r.stderr, /opd_audit_retrieval_telemetry_outcome_chk/,
    'BY NAME — the outcome CHECK, not some other constraint that happened to fire');
});

test('10.3 — THE REJECTED ROW DOES NOT PERSIST', () => {
  const n = sql(`SELECT count(*) FROM ${TELEM_TABLE} WHERE retrieval_run_id = '22222222-2222-2222-2222-222222222222';`);
  assert.deepEqual(n, ['0'], 'nothing was written — the refusal is not advisory');
  // …and the table still holds exactly the legal row from 10.1, so the failure did not roll back more.
  const all = sql(`SELECT count(*) FROM ${TELEM_TABLE};`);
  assert.deepEqual(all, ['1'], 'the legal row survives the rejected one');
});

test('10.3b — the mirror: an outcome-required state WITH an outcome inserts, so the CHECK is not simply refusing everything', () => {
  sql(`INSERT INTO ${TELEM_TABLE} (${ROW_COLS})
       VALUES ('33333333-3333-3333-3333-333333333333', 'primary', 'opd_audit_worker', 'inv-10', 'cdmss', NULL, 1, 'retrieval_complete', now(), 'success');`);
  assert.deepEqual(sql(`SELECT retrieval_outcome FROM ${TELEM_TABLE} WHERE retrieval_run_id = '33333333-3333-3333-3333-333333333333';`), ['success']);
  // And the reverse violation is refused too: `started` may NOT carry an outcome.
  const r = sqlExpectingError(`INSERT INTO ${TELEM_TABLE} (${ROW_COLS})
       VALUES ('44444444-4444-4444-4444-444444444444', 'primary', 'opd_audit_worker', 'inv-10', 'cdmss', NULL, 1, 'started', now(), 'success');`);
  assert.notEqual(r.status, 0);
  assert.match(r.stderr, /opd_audit_retrieval_telemetry_outcome_chk/, 'the same named CHECK, in the other direction');
});

test('10.4 — MISSING POSTGRESQL BINARIES FAIL LOUDLY, they never silently skip the proof', () => {
  // findPgBin is driven with an environment that has no PostgreSQL anywhere, and must THROW.
  const empty = mkdtempSync(join(tmpdir(), 'cdmss-proof10-nopg-'));
  try {
    // No PGBIN, an empty PATH, and NO absolute fallback roots — a machine with no PostgreSQL.
    const nowhere: PgSearch = { pgbin: undefined, path: empty, optRoots: [], debianRoot: undefined, pgsqlBin: undefined };
    assert.throws(() => findPgBin(nowhere), (e: unknown) => {
      assert.ok(e instanceof Error);
      assert.match(e.message, /proof 10 needs a local PostgreSQL/, 'the failure names what is missing');
      assert.match(e.message, /initdb, pg_ctl, psql/, 'and which tools');
      assert.match(e.message, /not simulated/, 'and states plainly that nothing was simulated in its place');
      return true;
    });
    // And the real search DOES find one on this machine, so the negative above is not vacuous.
    assert.ok(findPgBin().length > 0, 'the real search still resolves — 10.4 proves absence, not breakage');
  } finally {
    rmSync(empty, { recursive: true, force: true });
  }
});

test('10.4b — a timeout and a non-zero exit are BOTH named failures, never swallowed', () => {
  const fakeTimeout: PgRunner = () => ({ status: null, stdout: '', stderr: 'boom', timedOut: true });
  assert.throws(() => must(fakeTimeout, 'psql', ['-c', 'x'], 1234),
    /proof 10: psql -c x TIMED OUT after 1234 ms \(killed\); stderr: boom/);
  const fakeFail: PgRunner = () => ({ status: 2, stdout: '', stderr: 'syntax error', timedOut: false });
  assert.throws(() => must(fakeFail, 'initdb', ['-D', 'd'], 10),
    /proof 10: initdb -D d exited 2; stderr: syntax error/);
});

test('10.5 — NO ENVIRONMENT DATABASE URL IS READ: the cluster is reached only over its own loopback port', () => {
  // The proof-10 harness names no environment connection string anywhere in its own source, and
  // every psql invocation carries an explicit -h 127.0.0.1 and the cluster's own random port.
  const src = readFileSync(new URL('./retrieval-outcome-discrimination.test.ts', import.meta.url), 'utf8');
  const proof10 = src.slice(0, src.indexOf('// PROOF 14'));
  for (const name of ['DATABASE_URL', 'POSTGRES_URL', 'PGDATABASE', 'PGHOST', 'PGPORT', 'PGPASSWORD', 'NEON']) {
    assert.equal(proof10.includes(name), false, `proof 10 must not read ${name}`);
  }
  // Positively: the connection is loopback and the port is the disposable cluster's.
  assert.ok(cluster.c, 'the cluster is up');
  assert.ok(cluster.c.port >= 20000 && cluster.c.port < 40000, 'a random high port, chosen by this harness');
  assert.match(proof10, /'-h', '127\.0\.0\.1', '-p', String\(cluster\.c\.port\)/, 'every psql call is pinned to it');
});

test('10.6 — SHUTDOWN AND DIRECTORY REMOVAL ARE VERIFIED, and an unverified stop deletes nothing', () => {
  // The real teardown runs in `after()`; its rules are proven here with fakes, so the assertions do
  // not depend on tearing the live cluster down early.
  const dirA = mkdtempSync(join(tmpdir(), 'cdmss-proof10-fake-'));
  const stopsCleanly: PgRunner = (tool, args) => {
    if (tool === 'pg_ctl' && args.includes('stop')) return { status: 0, stdout: 'server stopped', stderr: '', timedOut: false };
    if (tool === 'pg_ctl' && args.includes('status')) return { status: 3, stdout: 'no server running', stderr: '', timedOut: false };
    return { status: 0, stdout: '', stderr: '', timedOut: false };
  };
  const okResult = teardown({ dir: dirA, data: join(dirA, 'data'), port: 1, started: true }, stopsCleanly);
  assert.deepEqual(okResult, { stopStatus: 0, verifiedStopped: true, deleted: true });
  assert.equal(existsSync(dirA), false, 'the directory is gone, and removal was confirmed');

  const dirB = mkdtempSync(join(tmpdir(), 'cdmss-proof10-fake-'));
  const refusesToStop: PgRunner = (tool, args) => {
    if (tool === 'pg_ctl' && args.includes('stop')) return { status: 1, stdout: '', stderr: 'could not stop', timedOut: false };
    if (tool === 'pg_ctl' && args.includes('status')) return { status: 0, stdout: 'server is running', stderr: '', timedOut: false };
    return { status: 0, stdout: '', stderr: '', timedOut: false };
  };
  try {
    assert.throws(() => teardown({ dir: dirB, data: join(dirB, 'data'), port: 1, started: true }, refusesToStop),
      (e: unknown) => {
        assert.ok(e instanceof Error);
        assert.match(e.message, /SHUTDOWN NOT VERIFIED/);
        assert.match(e.message, /LEFT IN PLACE for a human/);
        assert.ok(e.message.includes(dirB), 'and it names the directory');
        return true;
      });
    assert.equal(existsSync(dirB), true, 'NOTHING WAS DELETED — an orphaned directory beats an orphaned process');
  } finally {
    rmSync(dirB, { recursive: true, force: true });
  }
});

test('10.6b — the live cluster is torn down and verified by `after()`', { skip: false }, () => {
  // Asserted at the end of the run by `after()` itself; this test pins that the hook exists and
  // that the recorded teardown, once it has run, reports a verified stop and a confirmed removal.
  const src = readFileSync(new URL('./retrieval-outcome-discrimination.test.ts', import.meta.url), 'utf8');
  assert.match(src, /if \(cluster\.c\) cluster\.torn = teardown\(cluster\.c, cluster\.run\);/,
    'after() tears the live cluster down through the same verify-then-delete path');
});

// ════════════════════════════════════════════════════════════════════════════════════════════════
// PROOF 14 — EXTERNAL BEHAVIOUR ON EVERY SWALLOW ARM
//
// A retrieval that FOUND NOTHING and a retrieval that FAILED produce the same empty result at every
// site below. Only the recorded outcome tells them apart, and §3 requires that be proven by
// EXTERNAL BEHAVIOUR on each arm — not by reading the comment that claims it. That is the defect
// class that held proof 23 and that mutation row M2 exposed in 22.2.
//
// ⚠️ THE LOOPBACK EMBEDDINGS STUB IS V'S AUTHORIZATION (§2a, 21 Aug), TAKEN UNDER HIS OWN AUTHORITY
// AND RECORDED FOR SAUL TO RULE ON. The argument, reproduced: Rep 43 lists "live service" as a §6
// stop condition, and the SAME ruling MANDATES a "real disposable loopback PostgreSQL" for proof
// 10. "Live service" therefore cannot mean any service — it must mean SHARED or EXTERNAL ones. This
// stub is the same shape Saul already required, applied to a different dependency.
//
// It exists because `lib/llm.ts:41` builds an OpenAI client whose transport does NOT pass through
// `globalThis.fetch` — probed, not assumed: with a fetch stub installed before the first import and
// a valid base URL, the call still failed with `Connection error` and the stub saw no request at
// all. That is Rep 43's own finding #2. `retrieve()`'s `queryEmbedding` short-circuit exists but is
// passed only by normative-grounding and even-ground, never by any of the four swallow sites.
//
// Conditions 1-5 are met by `embedStub` below; condition 6 is test `14.0`; condition 7 is the
// evidence document.
// ════════════════════════════════════════════════════════════════════════════════════════════════

/** What the stub should do on the next embed call. Set per arm, never global state across files. */
type EmbedMode = 'ok' | 'fail';
const embedStub: {
  server: Server | null; port: number; mode: EmbedMode;
  embedCalls: number; chatCalls: number; lastPaths: string[];
} = { server: null, port: 0, mode: 'ok', embedCalls: 0, chatCalls: 0, lastPaths: [] };

/** 768 dimensions — `nomic-embed-text`'s width, which is what the `embedding` column expects. */
const FAKE_VECTOR = Array.from({ length: 768 }, (_, i) => ((i % 17) - 8) / 100);

/**
 * Start the disposable loopback embeddings stub. Bound to 127.0.0.1 on an OS-assigned high port,
 * started and stopped inside this file's lifecycle, exactly as proof 10's PostgreSQL is (§2a.1).
 *
 * ⚠️ FAILS LOUDLY (§2a.4). A bind failure rejects, which fails `before()` and therefore every test
 * in this file. It never degrades to a passing test with the arms unexercised.
 */
function startEmbedStub(): Promise<void> {
  return new Promise((resolve, reject) => {
    const server = createServer((req, res) => {
      const path = req.url ?? '';
      embedStub.lastPaths.push(path);
      let body = '';
      req.on('data', (c) => { body += c; });
      req.on('end', () => {
        if (/embeddings/.test(path)) {
          embedStub.embedCalls++;
          if (embedStub.mode === 'fail') {
            // A provider that is reachable and refuses. `embedQuery` throws, `retrieve()` throws,
            // and the swallow site under test is reached exactly as it is in production.
            res.writeHead(500, { 'content-type': 'application/json' });
            res.end(JSON.stringify({ error: { message: 'embeddings unavailable (proof 14 stub)' } }));
            return;
          }
          res.writeHead(200, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ object: 'list', model: 'nomic-embed-text', data: [{ object: 'embedding', index: 0, embedding: FAKE_VECTOR }], usage: { prompt_tokens: 1, total_tokens: 1 } }));
          return;
        }
        if (/chat\/completions/.test(path)) {
          // Query EXPANSION runs before retrieval unless skipExpand is set, and the swallow sites do
          // not set it. Answering here keeps expansion on its normal path instead of leaving it to
          // fail and change what the arm under test is measuring.
          embedStub.chatCalls++;
          res.writeHead(200, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ id: 'x', object: 'chat.completion', choices: [{ index: 0, message: { role: 'assistant', content: '' }, finish_reason: 'stop' }], usage: {} }));
          return;
        }
        res.writeHead(404, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ error: { message: `proof 14 stub: unrouted path ${path}` } }));
      });
    });
    server.once('error', (e) => reject(new Error(`proof 14: the loopback embeddings stub could not bind: ${(e as Error).message}. The arms are NOT simulated in its place.`)));
    server.listen(0, '127.0.0.1', () => {
      embedStub.server = server;
      embedStub.port = (server.address() as AddressInfo).port;
      resolve();
    });
  });
}

/** Stop, VERIFY no listener survives, and fail loudly rather than leaving one behind (§2a.5). */
function stopEmbedStub(): Promise<void> {
  return new Promise((resolve, reject) => {
    const server = embedStub.server;
    if (!server) { resolve(); return; }
    server.close((err) => {
      if (err) { reject(new Error(`proof 14: the embeddings stub did not close: ${err.message}. The listener is LEFT IN PLACE for a human on 127.0.0.1:${embedStub.port}.`)); return; }
      if (server.listening) { reject(new Error(`proof 14: the embeddings stub still reports listening after close on 127.0.0.1:${embedStub.port}`)); return; }
      embedStub.server = null;
      resolve();
    });
  });
}

// ── the transports each arm controls ────────────────────────────────────────────────────────────
const VECTOR_SQL = /ROW_NUMBER\(\) OVER \(ORDER BY embedding <=>/;
const BM25_SQL = /ROW_NUMBER\(\) OVER \(ORDER BY ts_rank_cd\(text/;
const HYDRATE_SQL = /SELECT id, source, book, chapter, section, page_start/;
const TERMINAL_SQL = /SET persistence_state = 'retrieval_complete'/;
const LVC_RECS_SQL = /FROM lvc_recommendations/;

const LVC_TELE = {
  ctx: { invocationId: 'inv-14-lvc', route: 'lvc_appropriateness', routeClass: 'route', deploymentSha: null, vercelRequestId: null, startedAt: '2026-08-12T00:00:00.000Z', routingFlags: {}, labExperimentId: null },
  route: 'lvc_appropriateness', persistenceIntent: 'never_persists',
} as never;

/** One corpus row, in the shape the hydrate SELECT returns. */
const chunk = (id: number) => ({
  id, source: 'choosing-wisely', book: 'CW-AAFP', chapter: null, section: null, page_start: null,
  page_end: null, item_number: 'r1', chunk_type: 'recommendation',
  text: `avoid montelukast for viral URTI (statement ${id})`, token_count: 12, similarity: 0.7,
});

/** The recorded outcome on the role's terminal row — $3 at the wire, read from the manifest. */
function outcomeOf(call: { params: unknown[] }): string {
  return (JSON.parse(String(call.params[20])) as { retrieval_outcome: string }).retrieval_outcome;
}

/**
 * Drive the REAL `matchLowValueCare` → `defaultRecall` with the corpus answering as `corpus` says.
 * Returns what the caller externally observed and what reached the telemetry transport.
 */
async function driveLvc(corpus: 'hits' | 'none' | 'embed-fails', recsAnswer?: Record<string, unknown>[] | Error) {
  const { installDbStub } = await import('./telemetry-db-stub');
  const db = installDbStub();
  db.on(TERMINAL_SQL, [{ row_revision: 1 }]);
  db.on(LVC_RECS_SQL, recsAnswer ?? [{ id: 'r1', keywords: ['montelukast'], category: 'rx' }]);
  if (corpus === 'hits') {
    db.on(VECTOR_SQL, [{ id: 1, rank: 1 }]);
    db.on(BM25_SQL, [{ id: 1, rank: 1 }]);
    db.on(HYDRATE_SQL, [chunk(1)]);
  } else {
    db.on(VECTOR_SQL, []);
    db.on(BM25_SQL, []);
    db.on(HYDRATE_SQL, []);
  }
  embedStub.mode = corpus === 'embed-fails' ? 'fail' : 'ok';
  const { matchLowValueCare } = await import('../lvc');
  let returned: unknown;
  let threw: unknown;
  try {
    returned = await matchLowValueCare({
      scenario: 'montelukast for viral URTI', proposedActions: ['montelukast'], trace: false, telemetry: LVC_TELE,
    } as never, {});
  } catch (e) { threw = e; }
  embedStub.mode = 'ok';
  return { db, returned, threw, terminals: db.matching(TERMINAL_SQL) };
}

// ══ §2a condition 6 — the stub is demonstrably IN the path ═════════════════════════════════════

test('14.0 — THE LOOPBACK EMBEDDINGS STUB IS IN THE PATH: the production embed call reaches it', async () => {
  const before = embedStub.embedCalls;
  const r = await driveLvc('hits');
  assert.ok(embedStub.embedCalls > before,
    'the embed call reached the stub — without this a regression could route around it and leave every arm below unexercised');
  assert.ok(embedStub.lastPaths.some((p) => /\/v1\/embeddings$/.test(p)), 'on the OpenAI-compatible embeddings path');
  assert.equal(r.terminals.length, 1, 'and the leg completed to its terminal write');
  // Loopback only. Nothing external, no shared database (§2a.3).
  assert.match(String(process.env.OLLAMA_BASE_URL), /^http:\/\/127\.0\.0\.1:\d+$/, 'bound to 127.0.0.1 on a high port');
  assert.ok(embedStub.port >= 1024, 'an OS-assigned high port');
});

// ══ §3 — LVC SEMANTIC SWALLOW: success · zero hits · retrieval failure ═════════════════════════

test('14.1 — LVC semantic swallow, SUCCESS: the row records `success` and the recall returns', async () => {
  const r = await driveLvc('hits');
  assert.equal(r.threw, undefined, 'no throw — the recall is the product');
  assert.equal(r.terminals.length, 1);
  assert.equal(outcomeOf(r.terminals[0]), 'success');
});

test('14.2 — LVC semantic swallow, ZERO HITS: `zero_hits`, and it is NOT `retrieval_failure`', async () => {
  const r = await driveLvc('none');
  assert.equal(r.threw, undefined);
  assert.equal(r.terminals.length, 1);
  assert.equal(outcomeOf(r.terminals[0]), 'zero_hits',
    'a SUCCESSFUL retrieval that found nothing');
  assert.notEqual(outcomeOf(r.terminals[0]), 'retrieval_failure');
});

test('14.3 — LVC semantic swallow, RETRIEVAL FAILURE: the exception is swallowed, the OUTCOME is not', async () => {
  const r = await driveLvc('embed-fails');
  // EXTERNAL BEHAVIOUR: the caller still receives a result. That is the swallow, and it is unchanged.
  assert.equal(r.threw, undefined, 'the semantic leg swallows — a recall failure must not fail the surface');
  assert.ok(r.returned !== undefined, 'and a result is still returned');
  assert.equal(r.terminals.length, 1);
  assert.equal(outcomeOf(r.terminals[0]), 'retrieval_failure',
    'but the row says it FAILED — which is the only thing distinguishing it from 14.2\'s empty result');
});

test('14.3b — the three LVC arms are mutually distinguishable, which is the whole point', async () => {
  const outcomes = [
    outcomeOf((await driveLvc('hits')).terminals[0]),
    outcomeOf((await driveLvc('none')).terminals[0]),
    outcomeOf((await driveLvc('embed-fails')).terminals[0]),
  ];
  assert.deepEqual(outcomes, ['success', 'zero_hits', 'retrieval_failure']);
  assert.equal(new Set(outcomes).size, 3, 'three arms, three distinct recorded facts');
});

// ══ §3 — BOTH OUTER defaultRecall SQL BRANCHES record failure AND RETHROW ══════════════════════

test('14.4 — outer defaultRecall SQL branch (NO region filter): records `retrieval_failure` and RETHROWS', async () => {
  const { classedError } = await import('./telemetry-db-stub');
  const r = await driveLvc('hits', classedError('lvc_recommendations unavailable', '57P01'));
  assert.ok(r.threw instanceof Error, 'the error RETHROWS — this branch sits outside the semantic leg\'s try');
  assert.match(String((r.threw as Error).message), /lvc_recommendations unavailable/, 'and it is the ORIGINAL error');
  assert.equal(r.terminals.length, 1, 'and the outcome was recorded BEFORE the error left the function');
  assert.equal(outcomeOf(r.terminals[0]), 'retrieval_failure');
});

test('14.5 — outer defaultRecall SQL branch (WITH region filter) behaves identically', async () => {
  const { installDbStub, classedError } = await import('./telemetry-db-stub');
  const db = installDbStub();
  db.on(TERMINAL_SQL, [{ row_revision: 1 }]);
  db.on(/FROM lvc_recommendations WHERE status = 'active' AND region = ANY/, classedError('region branch down', '57P01'));
  db.on(LVC_RECS_SQL, classedError('region branch down', '57P01'));
  embedStub.mode = 'ok';
  const { matchLowValueCare } = await import('../lvc');
  let threw: unknown;
  try {
    await matchLowValueCare({
      scenario: 'montelukast for viral URTI', proposedActions: ['montelukast'], trace: false,
      regionFilter: ['IN'], telemetry: LVC_TELE,
    } as never, {});
  } catch (e) { threw = e; }
  assert.ok(threw instanceof Error, 'the region-filtered branch rethrows too');
  assert.match(String((threw as Error).message), /region branch down/, 'the original error, unchanged');
  const terminals = db.matching(TERMINAL_SQL);
  assert.equal(terminals.length, 1);
  assert.equal(outcomeOf(terminals[0]), 'retrieval_failure');
  // The region-filtered statement really was the one that ran.
  assert.ok(db.matching(/region = ANY/).length >= 1, 'the ANY($1) form was issued, not the unfiltered one');
});

// ══ §3 — SUCCESS RECORDS EXACTLY ONE TERMINAL OUTCOME, NEVER TWO ═══════════════════════════════

test('14.6 — SUCCESS RECORDS EXACTLY ONE TERMINAL OUTCOME, never two', async () => {
  const r = await driveLvc('hits');
  assert.equal(r.terminals.length, 1, 'one terminal write for the lvc_recall role, not two');
  assert.equal(outcomeOf(r.terminals[0]), 'success');
  // And the row advanced exactly once: a second write would be a second revision on the same run.
  const runIds = new Set(r.terminals.map((c) => String(c.params[0])));
  assert.equal(runIds.size, 1, 'one run id');
});

// ══ §3 — PRIMARY and NORMATIVE swallow, through the real `auditOpdNote` ════════════════════════

const AUDIT_TELE = {
  ctx: { invocationId: 'inv-14-audit', route: 'opd_audit_worker', routeClass: 'worker', deploymentSha: null, vercelRequestId: null, startedAt: '2026-08-12T00:00:00.000Z', routingFlags: {}, labExperimentId: null },
  route: 'opd_audit_worker', persistenceIntent: 'will_persist',
} as never;

const AUDIT_ROW = {
  uid: 'uid-14-0001', consult_uid: 'consult-14', doctor_uid: 'doctor-14',
  note_text: 'Fever 3 days, sore throat. Dx: viral URTI. Rx: montelukast 10mg OD.',
  created_at: '2026-08-12T00:00:00.000Z',
};

/**
 * Drive the REAL, PLAN-FREE `auditOpdNote` — no fault plan, so both legs run production's own
 * `defaultRetrieve` / `normativeChannelRetrieve` against the loopback stub and the corpus answers
 * below. Returns each role's terminal row.
 */
async function driveAudit(corpus: 'hits' | 'none' | 'embed-fails') {
  const KEY = 'CDMSS_TELEMETRY_HMAC_KEY';
  const prev = process.env[KEY];
  process.env[KEY] = 'proof-14-key';
  try {
    const { installDbStub } = await import('./telemetry-db-stub');
    const db = installDbStub();
    db.on(TERMINAL_SQL, [{ row_revision: 1 }]);
    if (corpus === 'hits') {
      db.on(VECTOR_SQL, [{ id: 1, rank: 1 }]);
      db.on(BM25_SQL, [{ id: 1, rank: 1 }]);
      db.on(HYDRATE_SQL, [chunk(1)]);
    } else {
      db.on(VECTOR_SQL, []); db.on(BM25_SQL, []); db.on(HYDRATE_SQL, []);
    }
    embedStub.mode = corpus === 'embed-fails' ? 'fail' : 'ok';
    const { auditOpdNote } = await import('../opd-note-audit');
    let threw: unknown;
    let audit: unknown;
    try {
      audit = await auditOpdNote(AUDIT_ROW, { telemetry: AUDIT_TELE, evalNormativeChannel: true, trace: false } as never);
    } catch (e) { threw = e; }
    embedStub.mode = 'ok';
    const terminals = db.matching(TERMINAL_SQL);
    const byRole = (role: string) => terminals.find((c) => (JSON.parse(String(c.params[20])) as { operational: { retrieval_role: string } }).operational.retrieval_role === role);
    return { db, threw, audit, terminals, primary: byRole('primary'), normative: byRole('normative_channel') };
  } finally {
    if (prev === undefined) delete process.env[KEY]; else process.env[KEY] = prev;
  }
}

test('14.7 — PRIMARY swallow, all three arms: success · zero hits · retrieval failure', async () => {
  const hits = await driveAudit('hits');
  assert.ok(hits.primary, 'the primary terminal was written');
  assert.equal(outcomeOf(hits.primary), 'success');

  const none = await driveAudit('none');
  assert.ok(none.primary);
  assert.equal(outcomeOf(none.primary), 'zero_hits', 'found nothing — and said so');

  const failed = await driveAudit('embed-fails');
  assert.ok(failed.primary, 'the terminal is STILL written when retrieval failed');
  assert.equal(outcomeOf(failed.primary), 'retrieval_failure');

  // EXTERNAL BEHAVIOUR: the audit never rejects on any arm — the swallow is unchanged.
  for (const r of [hits, none, failed]) assert.equal(r.threw, undefined, 'the audit does not reject');
  assert.equal(new Set([outcomeOf(hits.primary), outcomeOf(none.primary), outcomeOf(failed.primary)]).size, 3,
    'three arms, three distinct recorded facts');
});

test('14.8 — NORMATIVE swallow, all three arms: success · zero hits · retrieval failure', async () => {
  const hits = await driveAudit('hits');
  assert.ok(hits.normative, 'the normative terminal was written');
  assert.equal(outcomeOf(hits.normative), 'success');

  const none = await driveAudit('none');
  assert.ok(none.normative);
  assert.equal(outcomeOf(none.normative), 'zero_hits');

  const failed = await driveAudit('embed-fails');
  assert.ok(failed.normative, 'the normative terminal is STILL written when retrieval failed');
  assert.equal(outcomeOf(failed.normative), 'retrieval_failure');

  assert.equal(new Set([outcomeOf(hits.normative), outcomeOf(none.normative), outcomeOf(failed.normative)]).size, 3);
});

test('14.9 — SUCCESS records exactly ONE terminal outcome PER ROLE, never two', async () => {
  const r = await driveAudit('hits');
  assert.equal(r.terminals.length, 2, 'two roles, two rows — and not four');
  const runIds = r.terminals.map((c) => String(c.params[0]));
  assert.equal(new Set(runIds).size, 2, 'one row per run id: no role was written twice');
  assert.deepEqual([outcomeOf(r.primary!), outcomeOf(r.normative!)], ['success', 'success']);
});

// ══ §3 — labRetrieve's TWO ERROR FORMS, and the MULTI-QUERY variant swallow ════════════════════

const LAB_CTX = { invocationId: 'inv-14-lab', route: 'mcp_lab_retrieve', routeClass: 'mcp', deploymentSha: null, vercelRequestId: null, startedAt: '2026-08-12T00:00:00.000Z', routingFlags: {}, labExperimentId: null } as never;

/** Drive the real `lab_retrieve` tool. `cohere` routes the rerank call to a local 404 — no egress. */
async function driveLabRetrieve(args: Record<string, unknown>, opts: { corpus?: 'hits' | 'none'; corpusError?: Error; cohere404?: boolean; embedFails?: boolean } = {}) {
  const { installDbStub } = await import('./telemetry-db-stub');
  const db = installDbStub();
  db.on(TERMINAL_SQL, [{ row_revision: 1 }]);
  if (opts.corpusError) {
    // The HYDRATE read, deliberately: `retrieve()` handles a failing vector or bm25 leg on its own,
    // so a per-leg error would never reach labRetrieve's catch and would test nothing.
    db.on(VECTOR_SQL, [{ id: 1, rank: 1 }, { id: 2, rank: 2 }]);
    db.on(BM25_SQL, [{ id: 1, rank: 1 }, { id: 2, rank: 2 }]);
    db.on(HYDRATE_SQL, opts.corpusError);
  } else if (opts.corpus === 'hits') {
    // TWO candidates, not one: with a single candidate the reranker is skipped entirely, so a
    // backend error could never arise and 14.10 would pass without exercising anything.
    db.on(VECTOR_SQL, [{ id: 1, rank: 1 }, { id: 2, rank: 2 }]);
    db.on(BM25_SQL, [{ id: 1, rank: 1 }, { id: 2, rank: 2 }]);
    db.on(HYDRATE_SQL, [chunk(1), chunk(2)]);
  } else {
    db.on(VECTOR_SQL, []); db.on(BM25_SQL, []); db.on(HYDRATE_SQL, []);
  }
  // ⚠️ NO EGRESS. Every non-database request is answered here; a cohere rerank gets a local 404,
  // which is what raises the NAMED RerankBackendMissing. Nothing leaves this machine.
  const stubbed = globalThis.fetch;
  const external: string[] = [];
  globalThis.fetch = (async (input: unknown, init?: unknown) => {
    const url = typeof input === 'string' ? input : String((input as { url?: string })?.url ?? input);
    if (/cohere/i.test(url)) { external.push(url); return new Response('not found', { status: 404 }); }
    return (stubbed as (a: unknown, b?: unknown) => Promise<Response>)(input, init);
  }) as typeof fetch;
  if (opts.embedFails) embedStub.mode = 'fail';
  try {
    const { callLabTool } = await import('../mcp-tools');
    let result: unknown;
    let threw: unknown;
    try { result = await callLabTool('lab_retrieve', args, LAB_CTX); } catch (e) { threw = e; }
    return { db, result, threw, external, terminals: db.matching(TERMINAL_SQL) };
  } finally {
    globalThis.fetch = stubbed;
    embedStub.mode = 'ok';
  }
}

test('14.10 — labRetrieve TYPED error: a RerankBackendError still returns the EXISTING result form, never a throw', async () => {
  const r = await driveLabRetrieve({ query: 'montelukast viral urti', rerankBackend: 'cohere', topK: 4 }, { corpus: 'hits', cohere404: true });
  assert.equal(r.threw, undefined, 'a typed backend error does NOT propagate — it becomes a result');
  const res = r.result as { ok?: boolean; error?: string; isError?: boolean; content?: unknown };
  assert.ok(res !== undefined, 'a ToolResult was returned');
  const asText = JSON.stringify(res);
  assert.match(asText, /RerankBackend(Missing|Unreachable|Unhealthy)/,
    'and it names the backend failure — surfaced, never a silent fallback');
  // The outcome was recorded before the result was formed.
  assert.equal(r.terminals.length, 1);
  assert.equal(outcomeOf(r.terminals[0]), 'retrieval_failure');
  assert.ok(r.external.every((u) => /cohere/i.test(u)), 'the only non-database request was the cohere one, answered locally');
  // The discriminator against 14.11: the typed arm is labRetrieve's OWN `err(...)`, not a rethrow.
  assert.match(asText, /RerankBackend/, 'the typed arm names the backend; the generic arm carries the original error');
});

test('14.11 — labRetrieve GENERIC error: the ORIGINAL error still throws, unchanged', async () => {
  // An embedding failure, which is NOT a RerankBackendError. `retrieve()` handles a failing vector,
  // bm25 or hydrate leg on its own, so those never reach labRetrieve's catch; the embed call is the
  // generic failure that genuinely escapes it.
  const r = await driveLabRetrieve({ query: 'montelukast viral urti', topK: 4 }, { corpus: 'hits', embedFails: true });
  // ⚠️ OBSERVED AT THE EXPORTED BOUNDARY. `labRetrieve` is module-private; `callLabTool` wraps the
  // dispatch and converts a rethrow into an `isError` result. So what a rethrow looks like from
  // outside is an isError result carrying the ORIGINAL error text — which is exactly what
  // distinguishes it from 14.10's typed arm, where `labRetrieve` returns `err(...)` itself and the
  // text names the backend instead.
  const res = r.result as { isError?: boolean; content?: { text?: string }[] };
  assert.equal(res.isError, true, 'the generic error propagated out of labRetrieve');
  const text = String(res.content?.[0]?.text ?? '');
  assert.match(text, /embeddings unavailable \(proof 14 stub\)/, 'carrying the ORIGINAL error, not a replacement');
  assert.doesNotMatch(text, /RerankBackend/, 'and NOT via the typed-error path 14.10 covers');
  assert.equal(r.terminals.length, 1, 'the outcome was still recorded before it left');
  assert.equal(outcomeOf(r.terminals[0]), 'retrieval_failure',
    'so a caller that only saw the throw still has the row saying WHY');
});

test('14.12 — MULTI-QUERY variant swallow, all three arms: success · zero hits · retrieval failure', async () => {
  const hits = await driveLabRetrieve({ query: 'montelukast viral urti', multiQuery: true, topK: 4 }, { corpus: 'hits' });
  assert.ok(hits.terminals.length >= 1, 'the multi-query leg wrote its terminal');
  assert.equal(outcomeOf(hits.terminals[0]), 'success');

  const none = await driveLabRetrieve({ query: 'montelukast viral urti', multiQuery: true, topK: 4 }, { corpus: 'none' });
  assert.equal(outcomeOf(none.terminals[0]), 'zero_hits', 'every arm found nothing — which is not a failure');

  embedStub.mode = 'fail';
  const failed = await driveLabRetrieve({ query: 'montelukast viral urti', multiQuery: true, topK: 4 }, { corpus: 'hits' });
  embedStub.mode = 'ok';
  assert.ok(failed.terminals.length >= 1, 'and the terminal is still written when every arm failed');
  assert.equal(outcomeOf(failed.terminals[0]), 'retrieval_failure');

  assert.equal(new Set([outcomeOf(hits.terminals[0]), outcomeOf(none.terminals[0]), outcomeOf(failed.terminals[0])]).size, 3,
    'three arms, three distinct recorded facts');
});
